<?
define("HIDE_SIDEBAR", true);
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Каталог");
?><div style="width: 60%; margin-left: 20%; }">
	<div id="overlay">
		<div class="popup">
			<h2>Сайт в разработке</h2>
			<p>
				 Уважаемые, посетители сайта! Мы рады, что Вы заглянули к нам на сайт! <br>
				 Обращаем Ваше внимание, что сайт находится в разработке! <br>
 <strong>Вы можете продолжать совершать покупки и оставлять ваши заявки. </strong> <br>
				 Приносим свои извинения за временные неудобства. <br>
				 По всем интересующим Вас вопросам, мы готовы проконсультировать по телефонам: <br>
 <a href="tel:+7(4112)722511"> +7(4112)722511 </a> <br>
 <a href="tel:+79142722511"> +79142722511 </a> <br>
				 а также ответить на все ваши письма по электронной почте: <a href="mailto:logika1c@mail.ru">logika1c@mail.ru</a>.
			</p>
 <button class="close" title="Закрыть" onclick="document.getElementById('overlay').style.display='none';"></button>
		</div>
	</div>
	 <?$APPLICATION->IncludeComponent(
	"bitrix:catalog.search",
	"bootstrap_v6",
	Array(
		"ACTION_VARIABLE" => "action",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"BASKET_URL" => "/personal/basket.php",
		"CACHE_TIME" => "36000000",
		"CACHE_TYPE" => "A",
		"CHECK_DATES" => "N",
		"COMPONENT_TEMPLATE" => "bootstrap_v4",
		"CONVERT_CURRENCY" => "N",
		"DETAIL_URL" => "",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"DISPLAY_COMPARE" => "N",
		"DISPLAY_TOP_PAGER" => "N",
		"ELEMENT_SORT_FIELD" => "sort",
		"ELEMENT_SORT_FIELD2" => "id",
		"ELEMENT_SORT_ORDER" => "asc",
		"ELEMENT_SORT_ORDER2" => "desc",
		"HIDE_NOT_AVAILABLE" => "N",
		"HIDE_NOT_AVAILABLE_OFFERS" => "N",
		"IBLOCK_ID" => "53",
		"IBLOCK_TYPE" => "1c_catalog",
		"LINE_ELEMENT_COUNT" => "3",
		"NO_WORD_LOGIC" => "N",
		"OFFERS_LIMIT" => "5",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_TEMPLATE" => ".default",
		"PAGER_TITLE" => "Товары",
		"PAGE_ELEMENT_COUNT" => "30",
		"PRICE_CODE" => "",
		"PRICE_VAT_INCLUDE" => "Y",
		"PRODUCT_ID_VARIABLE" => "id",
		"PRODUCT_PROPERTIES" => "",
		"PRODUCT_PROPS_VARIABLE" => "prop",
		"PRODUCT_QUANTITY_VARIABLE" => "quantity",
		"PROPERTY_CODE" => array(0=>"",1=>"",),
		"RESTART" => "N",
		"SECTION_ID_VARIABLE" => "SECTION_ID",
		"SECTION_URL" => "",
		"SHOW_PRICE_COUNT" => "1",
		"USE_LANGUAGE_GUESS" => "Y",
		"USE_PRICE_COUNT" => "N",
		"USE_PRODUCT_QUANTITY" => "N",
		"USE_SEARCH_RESULT_ORDER" => "N",
		"USE_TITLE_RANK" => "N"
	)
);?>
</div>
<div class="main_catalog_container container">
	 <?$APPLICATION->IncludeComponent(
	"bitrix:catalog", 
	"bootstrap_v5", 
	array(
		"ACTION_VARIABLE" => "action",
		"ADD_ELEMENT_CHAIN" => "Y",
		"ADD_PICT_PROP" => "-",
		"ADD_PROPERTIES_TO_BASKET" => "Y",
		"ADD_SECTIONS_CHAIN" => "Y",
		"ADD_SECTION_CHAIN" => "Y",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"ALSO_BUY_ELEMENT_COUNT" => "4",
		"ALSO_BUY_MIN_BUYES" => "1",
		"BASKET_URL" => "/personal/cart/",
		"BIG_DATA_RCM_TYPE" => "similar_sell",
		"CACHE_FILTER" => "Y",
		"CACHE_GROUPS" => "Y",
		"CACHE_TIME" => "36000000",
		"CACHE_TYPE" => "A",
		"COMMON_ADD_TO_BASKET_ACTION" => "ADD",
		"COMMON_SHOW_CLOSE_POPUP" => "N",
		"COMPATIBLE_MODE" => "N",
		"CONVERT_CURRENCY" => "N",
		"DETAIL_ADD_DETAIL_TO_SLIDER" => "N",
		"DETAIL_ADD_TO_BASKET_ACTION" => array(
			0 => "ADD",
		),
		"DETAIL_ADD_TO_BASKET_ACTION_PRIMARY" => array(
			0 => "ADD",
		),
		"DETAIL_BACKGROUND_IMAGE" => "-",
		"DETAIL_BLOG_EMAIL_NOTIFY" => "N",
		"DETAIL_BLOG_URL" => "catalog_comments",
		"DETAIL_BLOG_USE" => "Y",
		"DETAIL_BRAND_PROP_CODE" => array(
			0 => "",
			1 => "BRAND_REF",
			2 => "",
		),
		"DETAIL_BRAND_USE" => "Y",
		"DETAIL_BROWSER_TITLE" => "-",
		"DETAIL_CHECK_SECTION_ID_VARIABLE" => "N",
		"DETAIL_DETAIL_PICTURE_MODE" => array(
			0 => "POPUP",
			1 => "MAGNIFIER",
		),
		"DETAIL_DISPLAY_NAME" => "N",
		"DETAIL_DISPLAY_PREVIEW_TEXT_MODE" => "E",
		"DETAIL_FB_APP_ID" => "",
		"DETAIL_FB_USE" => "Y",
		"DETAIL_IMAGE_RESOLUTION" => "16by9",
		"DETAIL_MAIN_BLOCK_PROPERTY_CODE" => array(
		),
		"DETAIL_META_DESCRIPTION" => "-",
		"DETAIL_META_KEYWORDS" => "-",
		"DETAIL_OFFERS_FIELD_CODE" => array(
			0 => "NAME",
			1 => "",
		),
		"DETAIL_OFFERS_PROPERTY_CODE" => array(
			0 => "ARTNUMBER",
			1 => "SIZES_SHOES",
			2 => "SIZES_CLOTHES",
			3 => "COLOR_REF",
			4 => "MORE_PHOTO",
			5 => "",
		),
		"DETAIL_PRODUCT_INFO_BLOCK_ORDER" => "sku,props",
		"DETAIL_PRODUCT_PAY_BLOCK_ORDER" => "rating,price,priceRanges,quantityLimit,quantity,buttons",
		"DETAIL_PROPERTY_CODE" => array(
			0 => "NALICHIE_KARTRIDERA",
			1 => "KLYUCH",
			2 => "SKOROST_PECHATI",
			3 => "TIP_PECHATI_",
			4 => "BLOG_POST_ID",
			5 => "CML2_ARTICLE",
			6 => "CML2_BASE_UNIT",
			7 => "BLOG_COMMENTS_CNT",
			8 => "CML2_MANUFACTURER",
			9 => "CML2_TRAITS",
			10 => "CML2_TAXES",
			11 => "CML2_ATTRIBUTES",
			12 => "SHIRINA_BUMAGI",
			13 => "CML2_BAR_CODE",
			14 => "INTERFEYSY",
			15 => "AVTOOTREZ",
			16 => "SKOROST_PECHATI_1",
			17 => "RESURS_PECHATNOY_GOLOVKI",
			18 => "AVTOOTREZ_CHEKA",
			19 => "DLINA_NAMOTKI_CHEKOVOY_LENTY",
			20 => "DIAMETR_RULONA_CHEKOVOY_LENTY",
			21 => "SHIRINA_CHEKA",
			22 => "PEREDACHA_DANNYKH",
			23 => "BESPROVODNAYA_PEREDACHA_DANNYKH",
			24 => "PODKLYUCHENIE_K_DENEZHNOMU_YASHCHIKU",
			25 => "PODKLYUCHENIE_K_DISPLEYU_POKUPATELYA",
			26 => "PODKLYUCHENIE_K_PITANIYU",
			27 => "RAZMERY_DLKHSHRKHVS",
			28 => "VES_BEZ_CHEKOVOY_LENTY",
			29 => "VREMYA_RABOTY_OT_AKKUMKLYATORA",
			30 => "PROGRAMMIRUEMYE_KLAVISHI",
			31 => "PEREMARKIRUEMYE_KLAVISHI",
			32 => "KOLICHESTVO_KLAVISH",
			33 => "DISPLEY",
			34 => "RAZRESHENIE_EKRANA",
			35 => "PROTSESSOR_KOMPYUTERA",
			36 => "OPERATSIONNAYA_SISTEMA",
			37 => "OBYEM_OPERATIVNOY_PAMYATI",
			38 => "OBYEM_FIZICHESKOY_PAMYATI",
			39 => "DOPOLNITELNAYA_PAMYAT",
			40 => "SETEVOE_PODKLYUCHENIE",
			41 => "SHIRINA_CHEKOVOY_LENTY",
			42 => "SKOROST_PECHATI_2",
			43 => "REZAK",
			44 => "ELEKTROPITANIE",
			45 => "AKKUMULYATOR",
			46 => "KOLICHESTVO_USB_PORTOV",
			47 => "VREMYA_RABOTY_AKB",
			48 => "VREMYA_RABOTY_OT_AKKUMKLYATORA_1",
			49 => "DOPOLNITELNYE_INTERFEYSY",
			50 => "TIP_",
			51 => "INTERFESY",
			52 => "SKOROST_SKANIROVANIYA",
			53 => "DALNOST_SKANIROVANIYA",
			54 => "TIP_SCHITYVAEMYKH_SHTRIKHKODOV",
			55 => "RASSTOYANIE_MEZHDU_SKANEROM_I_BAZOY",
			56 => "NEWPRODUCT",
			57 => "MANUFACTURER",
			58 => "MATERIAL",
			59 => "",
		),
		"DETAIL_SET_CANONICAL_URL" => "N",
		"DETAIL_SET_VIEWED_IN_COMPONENT" => "N",
		"DETAIL_SHOW_POPULAR" => "Y",
		"DETAIL_SHOW_SLIDER" => "N",
		"DETAIL_SHOW_VIEWED" => "Y",
		"DETAIL_STRICT_SECTION_CHECK" => "N",
		"DETAIL_USE_COMMENTS" => "N",
		"DETAIL_USE_VOTE_RATING" => "N",
		"DETAIL_VK_USE" => "N",
		"DETAIL_VOTE_DISPLAY_AS_RATING" => "rating",
		"DISABLE_INIT_JS_IN_COMPONENT" => "N",
		"DISCOUNT_PERCENT_POSITION" => "bottom-right",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"DISPLAY_TOP_PAGER" => "N",
		"ELEMENT_SORT_FIELD" => "SCALED_PRICE_1",
		"ELEMENT_SORT_FIELD2" => "id",
		"ELEMENT_SORT_ORDER" => "asc",
		"ELEMENT_SORT_ORDER2" => "desc",
		"FIELDS" => array(
			0 => "SCHEDULE",
			1 => "STORE",
			2 => "",
		),
		"FILTER_HIDE_ON_MOBILE" => "N",
		"FILTER_NAME" => "",
		"FILTER_VIEW_MODE" => "VERTICAL",
		"GIFTS_DETAIL_BLOCK_TITLE" => "Выберите один из подарков",
		"GIFTS_DETAIL_HIDE_BLOCK_TITLE" => "N",
		"GIFTS_DETAIL_PAGE_ELEMENT_COUNT" => "4",
		"GIFTS_DETAIL_TEXT_LABEL_GIFT" => "Подарок",
		"GIFTS_MAIN_PRODUCT_DETAIL_BLOCK_TITLE" => "Выберите один из товаров, чтобы получить подарок",
		"GIFTS_MAIN_PRODUCT_DETAIL_HIDE_BLOCK_TITLE" => "N",
		"GIFTS_MAIN_PRODUCT_DETAIL_PAGE_ELEMENT_COUNT" => "4",
		"GIFTS_MESS_BTN_BUY" => "Выбрать",
		"GIFTS_SECTION_LIST_BLOCK_TITLE" => "Подарки к товарам этого раздела",
		"GIFTS_SECTION_LIST_HIDE_BLOCK_TITLE" => "N",
		"GIFTS_SECTION_LIST_PAGE_ELEMENT_COUNT" => "4",
		"GIFTS_SECTION_LIST_TEXT_LABEL_GIFT" => "Подарок",
		"GIFTS_SHOW_DISCOUNT_PERCENT" => "Y",
		"GIFTS_SHOW_IMAGE" => "Y",
		"GIFTS_SHOW_NAME" => "Y",
		"GIFTS_SHOW_OLD_PRICE" => "Y",
		"HIDE_NOT_AVAILABLE" => "N",
		"HIDE_NOT_AVAILABLE_OFFERS" => "N",
		"IBLOCK_ID" => "53",
		"IBLOCK_TYPE" => "1c_catalog",
		"INCLUDE_SUBSECTIONS" => "Y",
		"INSTANT_RELOAD" => "N",
		"LABEL_PROP" => array(
			0 => "NALICHIE_KARTRIDERA",
		),
		"LABEL_PROP_MOBILE" => array(
		),
		"LABEL_PROP_POSITION" => "top-left",
		"LAZY_LOAD" => "N",
		"LINE_ELEMENT_COUNT" => "3",
		"LINK_ELEMENTS_URL" => "link.php?PARENT_ELEMENT_ID=#ELEMENT_ID#",
		"LINK_IBLOCK_ID" => "",
		"LINK_IBLOCK_TYPE" => "",
		"LINK_PROPERTY_SID" => "",
		"LIST_BROWSER_TITLE" => "-",
		"LIST_ENLARGE_PRODUCT" => "STRICT",
		"LIST_META_DESCRIPTION" => "-",
		"LIST_META_KEYWORDS" => "-",
		"LIST_OFFERS_FIELD_CODE" => array(
			0 => "NAME",
			1 => "PREVIEW_PICTURE",
			2 => "DETAIL_PICTURE",
			3 => "",
		),
		"LIST_OFFERS_LIMIT" => "0",
		"LIST_OFFERS_PROPERTY_CODE" => array(
			0 => "SIZES_SHOES",
			1 => "SIZES_CLOTHES",
			2 => "COLOR_REF",
			3 => "MORE_PHOTO",
			4 => "ARTNUMBER",
			5 => "",
		),
		"LIST_PRODUCT_BLOCKS_ORDER" => "price,props,sku,quantityLimit,quantity,buttons",
		"LIST_PRODUCT_ROW_VARIANTS" => "[{'VARIANT':'3','BIG_DATA':false},{'VARIANT':'3','BIG_DATA':false},{'VARIANT':'3','BIG_DATA':false}]",
		"LIST_PROPERTY_CODE" => array(
			0 => "NALICHIE_KARTRIDERA",
			1 => "KLYUCH",
			2 => "SKOROST_PECHATI",
			3 => "TIP_PECHATI_",
			4 => "BLOG_POST_ID",
			5 => "CML2_ARTICLE",
			6 => "CML2_BASE_UNIT",
			7 => "BLOG_COMMENTS_CNT",
			8 => "CML2_MANUFACTURER",
			9 => "CML2_TRAITS",
			10 => "CML2_TAXES",
			11 => "CML2_ATTRIBUTES",
			12 => "SHIRINA_BUMAGI",
			13 => "CML2_BAR_CODE",
			14 => "INTERFEYSY",
			15 => "AVTOOTREZ",
			16 => "SKOROST_PECHATI_1",
			17 => "RESURS_PECHATNOY_GOLOVKI",
			18 => "AVTOOTREZ_CHEKA",
			19 => "DLINA_NAMOTKI_CHEKOVOY_LENTY",
			20 => "DIAMETR_RULONA_CHEKOVOY_LENTY",
			21 => "SHIRINA_CHEKA",
			22 => "PEREDACHA_DANNYKH",
			23 => "BESPROVODNAYA_PEREDACHA_DANNYKH",
			24 => "PODKLYUCHENIE_K_DENEZHNOMU_YASHCHIKU",
			25 => "PODKLYUCHENIE_K_DISPLEYU_POKUPATELYA",
			26 => "PODKLYUCHENIE_K_PITANIYU",
			27 => "RAZMERY_DLKHSHRKHVS",
			28 => "VES_BEZ_CHEKOVOY_LENTY",
			29 => "VREMYA_RABOTY_OT_AKKUMKLYATORA",
			30 => "PROGRAMMIRUEMYE_KLAVISHI",
			31 => "PEREMARKIRUEMYE_KLAVISHI",
			32 => "KOLICHESTVO_KLAVISH",
			33 => "DISPLEY",
			34 => "RAZRESHENIE_EKRANA",
			35 => "PROTSESSOR_KOMPYUTERA",
			36 => "OPERATSIONNAYA_SISTEMA",
			37 => "OBYEM_OPERATIVNOY_PAMYATI",
			38 => "OBYEM_FIZICHESKOY_PAMYATI",
			39 => "DOPOLNITELNAYA_PAMYAT",
			40 => "SETEVOE_PODKLYUCHENIE",
			41 => "SHIRINA_CHEKOVOY_LENTY",
			42 => "SKOROST_PECHATI_2",
			43 => "REZAK",
			44 => "ELEKTROPITANIE",
			45 => "AKKUMULYATOR",
			46 => "KOLICHESTVO_USB_PORTOV",
			47 => "VREMYA_RABOTY_AKB",
			48 => "VREMYA_RABOTY_OT_AKKUMKLYATORA_1",
			49 => "DOPOLNITELNYE_INTERFEYSY",
			50 => "TIP_",
			51 => "INTERFESY",
			52 => "SKOROST_SKANIROVANIYA",
			53 => "DALNOST_SKANIROVANIYA",
			54 => "TIP_SCHITYVAEMYKH_SHTRIKHKODOV",
			55 => "RASSTOYANIE_MEZHDU_SKANEROM_I_BAZOY",
			56 => "NEWPRODUCT",
			57 => "SALELEADER",
			58 => "SPECIALOFFER",
			59 => "",
		),
		"LIST_PROPERTY_CODE_MOBILE" => array(
		),
		"LIST_SHOW_SLIDER" => "N",
		"LIST_SLIDER_INTERVAL" => "3000",
		"LIST_SLIDER_PROGRESS" => "N",
		"LOAD_ON_SCROLL" => "N",
		"MAIN_TITLE" => "",
		"MESSAGE_404" => "",
		"MESS_BTN_ADD_TO_BASKET" => "В корзину",
		"MESS_BTN_BUY" => "Купить",
		"MESS_BTN_COMPARE" => "Сравнение",
		"MESS_BTN_DETAIL" => "Подробнее",
		"MESS_BTN_SUBSCRIBE" => "Подписаться",
		"MESS_COMMENTS_TAB" => "Комментарии",
		"MESS_DESCRIPTION_TAB" => "Описание",
		"MESS_NOT_AVAILABLE" => "Под заказ ",
		"MESS_PRICE_RANGES_TITLE" => "Цены",
		"MESS_PROPERTIES_TAB" => "Характеристики",
		"MIN_AMOUNT" => "10",
		"OFFERS_CART_PROPERTIES" => array(
			0 => "SIZES_SHOES",
			1 => "SIZES_CLOTHES",
			2 => "COLOR_REF",
		),
		"OFFERS_SORT_FIELD" => "sort",
		"OFFERS_SORT_FIELD2" => "id",
		"OFFERS_SORT_ORDER" => "desc",
		"OFFERS_SORT_ORDER2" => "desc",
		"OFFER_ADD_PICT_PROP" => "MORE_PHOTO",
		"OFFER_TREE_PROPS" => array(
			0 => "SIZES_SHOES",
			1 => "SIZES_CLOTHES",
			2 => "COLOR_REF",
			3 => "",
		),
		"PAGER_BASE_LINK_ENABLE" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000000",
		"PAGER_SHOW_ALL" => "N",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_TEMPLATE" => "round",
		"PAGER_TITLE" => "Товары",
		"PAGE_ELEMENT_COUNT" => "12",
		"PARTIAL_PRODUCT_PROPERTIES" => "Y",
		"PRICE_CODE" => array(
			0 => "retail",
		),
		"PRICE_VAT_INCLUDE" => "N",
		"PRICE_VAT_SHOW_VALUE" => "N",
		"PRODUCT_DISPLAY_MODE" => "Y",
		"PRODUCT_ID_VARIABLE" => "id",
		"PRODUCT_PROPERTIES" => array(
		),
		"PRODUCT_PROPS_VARIABLE" => "prop",
		"PRODUCT_QUANTITY_VARIABLE" => "quantity",
		"PRODUCT_SUBSCRIPTION" => "Y",
		"QUANTITY_FLOAT" => "N",
		"SEARCH_CHECK_DATES" => "Y",
		"SEARCH_NO_WORD_LOGIC" => "Y",
		"SEARCH_PAGE_RESULT_COUNT" => "50",
		"SEARCH_RESTART" => "N",
		"SEARCH_USE_LANGUAGE_GUESS" => "Y",
		"SECTIONS_HIDE_SECTION_NAME" => "N",
		"SECTIONS_SHOW_PARENT_NAME" => "Y",
		"SECTIONS_VIEW_MODE" => "TILE",
		"SECTION_ADD_TO_BASKET_ACTION" => "ADD",
		"SECTION_BACKGROUND_IMAGE" => "-",
		"SECTION_COUNT_ELEMENTS" => "N",
		"SECTION_ID_VARIABLE" => "SECTION_ID",
		"SECTION_TOP_DEPTH" => "1",
		"SEF_FOLDER" => "/catalog/",
		"SEF_MODE" => "Y",
		"SET_LAST_MODIFIED" => "N",
		"SET_STATUS_404" => "Y",
		"SET_TITLE" => "Y",
		"SHOW_404" => "N",
		"SHOW_DEACTIVATED" => "N",
		"SHOW_DISCOUNT_PERCENT" => "Y",
		"SHOW_EMPTY_STORE" => "N",
		"SHOW_GENERAL_STORE_INFORMATION" => "N",
		"SHOW_MAX_QUANTITY" => "N",
		"SHOW_OLD_PRICE" => "N",
		"SHOW_PRICE_COUNT" => "1",
		"SHOW_TOP_ELEMENTS" => "N",
		"SIDEBAR_DETAIL_POSITION" => "right",
		"SIDEBAR_DETAIL_SHOW" => "Y",
		"SIDEBAR_PATH" => "/catalog/sidebar.php",
		"SIDEBAR_SECTION_POSITION" => "right",
		"SIDEBAR_SECTION_SHOW" => "N",
		"STORES" => array(
			0 => "2",
			1 => "",
		),
		"STORE_PATH" => "/store/#store_id#",
		"TEMPLATE_THEME" => "site",
		"TOP_ADD_TO_BASKET_ACTION" => "ADD",
		"USER_CONSENT" => "N",
		"USER_CONSENT_ID" => "0",
		"USER_CONSENT_IS_CHECKED" => "Y",
		"USER_CONSENT_IS_LOADED" => "N",
		"USER_FIELDS" => array(
			0 => "",
			1 => "",
		),
		"USE_ALSO_BUY" => "Y",
		"USE_BIG_DATA" => "Y",
		"USE_COMMON_SETTINGS_BASKET_POPUP" => "N",
		"USE_COMPARE" => "N",
		"USE_ELEMENT_COUNTER" => "N",
		"USE_ENHANCED_ECOMMERCE" => "N",
		"USE_FILTER" => "N",
		"USE_GIFTS_DETAIL" => "N",
		"USE_GIFTS_MAIN_PR_SECTION_LIST" => "N",
		"USE_GIFTS_SECTION" => "N",
		"USE_MAIN_ELEMENT_SECTION" => "N",
		"USE_MIN_AMOUNT" => "N",
		"USE_PRICE_COUNT" => "N",
		"USE_PRODUCT_QUANTITY" => "Y",
		"USE_SALE_BESTSELLERS" => "Y",
		"USE_STORE" => "N",
		"COMPONENT_TEMPLATE" => "bootstrap_v5",
		"SEF_URL_TEMPLATES" => array(
			"sections" => "",
			"section" => "#SECTION_CODE#/",
			"element" => "#SECTION_CODE#/#ELEMENT_CODE#/",
			"compare" => "compare/",
			"smart_filter" => "#SECTION_CODE#/filter/#SMART_FILTER_PATH#/apply/",
		)
	),
	false
);?>
</div><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>