<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Оформление заказа");
?>
<?if (IsModuleInstalled('sale')):?>
    <?$APPLICATION->IncludeComponent(
        "bitrix:sale.order.ajax",
        ".default",
        array(
            "PAY_FROM_ACCOUNT" => "Y",
            "COUNT_DELIVERY_TAX" => "N",
            "COUNT_DISCOUNT_4_ALL_QUANTITY" => "N",
            "ONLY_FULL_PAY_FROM_ACCOUNT" => "N",
            "ALLOW_AUTO_REGISTER" => "Y",
            "SEND_NEW_USER_NOTIFY" => "Y",
            "DELIVERY_NO_AJAX" => "N",
            "TEMPLATE_LOCATION" => "popup",
            "PROP_1" => "",
            "PATH_TO_BASKET" => "/personal/cart/",
            "PATH_TO_PERSONAL" => "/personal/",
            "PATH_TO_PAYMENT" => "/personal/payment/",
            "PATH_TO_ORDER" => "/personal/order_make/",
            "SET_TITLE" => "Y",
            "SHOW_ACCOUNT_NUMBER" => "Y",
            "DELIVERY_NO_SESSION" => "Y",
            "COMPATIBLE_MODE" => "N",
            "BASKET_POSITION" => "after",
            "BASKET_IMAGES_SCALING" => "adaptive",
            "SERVICES_IMAGES_SCALING" => "adaptive",
            "COMPONENT_TEMPLATE" => ".default",
            "DELIVERY_TO_PAYSYSTEM" => "d2p",
            "USE_PREPAYMENT" => "N",
            "USE_PRELOAD" => "Y",
            "ALLOW_USER_PROFILES" => "N",
            "ALLOW_NEW_PROFILE" => "undefined",
            "TEMPLATE_THEME" => "site",
            "SHOW_ORDER_BUTTON" => "final_step",
            "SHOW_TOTAL_ORDER_BUTTON" => "N",
            "SHOW_PAY_SYSTEM_LIST_NAMES" => "Y",
            "SHOW_PAY_SYSTEM_INFO_NAME" => "Y",
            "SHOW_DELIVERY_LIST_NAMES" => "Y",
            "SHOW_DELIVERY_INFO_NAME" => "Y",
            "SHOW_DELIVERY_PARENT_NAMES" => "Y",
            "SHOW_STORES_IMAGES" => "Y",
            "SKIP_USELESS_BLOCK" => "Y",
            "SHOW_BASKET_HEADERS" => "N",
            "DELIVERY_FADE_EXTRA_SERVICES" => "N",
            "SHOW_COUPONS_BASKET" => "Y",
            "SHOW_COUPONS_DELIVERY" => "Y",
            "SHOW_COUPONS_PAY_SYSTEM" => "Y",
            "SHOW_NEAREST_PICKUP" => "N",
            "DELIVERIES_PER_PAGE" => "8",
            "PAY_SYSTEMS_PER_PAGE" => "8",
            "PICKUPS_PER_PAGE" => "5",
            "SHOW_MAP_IN_PROPS" => "N",
            "PROPS_FADE_LIST_1" => array(
            ),
            "PROPS_FADE_LIST_2" => array(
            ),
            "PATH_TO_AUTH" => "/auth/",
            "DISABLE_BASKET_REDIRECT" => "N",
            "PRODUCT_COLUMNS_VISIBLE" => array(
                0 => "PREVIEW_PICTURE",
                1 => "PROPS",
            ),
            "ADDITIONAL_PICT_PROP_8" => "-",
            "ADDITIONAL_PICT_PROP_9" => "-",
            "ADDITIONAL_PICT_PROP_10" => "-",
            "PRODUCT_COLUMNS_HIDDEN" => array(
            ),
            "USE_YM_GOALS" => "N",
            "USE_CUSTOM_MAIN_MESSAGES" => "N",
            "USE_CUSTOM_ADDITIONAL_MESSAGES" => "N",
            "USE_CUSTOM_ERROR_MESSAGES" => "N",
            "USER_CONSENT" => "Y",
            "USER_CONSENT_ID" => "1",
            "USER_CONSENT_IS_CHECKED" => "Y",
            "USER_CONSENT_IS_LOADED" => "N",
        ),
        false
    );?>
<?endif?>
<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>